# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np  # Импортируем библиотеку numpy

# Получаем и выводим версию numpy
numpy_version = np.__version__

# Выводим версию numpy
print("Версия numpy:", numpy_version)


Версия numpy: 1.26.4


2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np  # Импортируем библиотеку numpy, которая используется для работы с массивами и матрицами

# Создаем нулевой вектор размера 10
zero_vector = np.zeros(10)

# Выводим полученный нулевой вектор
print(zero_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами

# Создаем вектор размера 7, заполненный числами 7
sevens_vector = np.full(7, 7)

# Выводим полученный вектор
print(sevens_vector)


[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами

# Создаем вектор с четными числами от 10 до 100 включительно
even_vector = np.arange(10, 101, 2)

# Выводим полученный вектор
print(even_vector)


[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами

# Создаем массив случайных чисел (например, из 10 элементов)
random_array = np.random.rand(10)

# Выводим оригинальный массив
print("Оригинальный массив:", random_array)

# Разворачиваем массив задом наперёд
reversed_array = random_array[::-1]

# Выводим развернутый массив
print("Развернутый массив:", reversed_array)



Оригинальный массив: [0.55566688 0.75198918 0.20754531 0.88628805 0.62965796 0.05183343
 0.98211267 0.42581565 0.23503865 0.79745032]
Развернутый массив: [0.79745032 0.23503865 0.42581565 0.98211267 0.05183343 0.62965796
 0.88628805 0.20754531 0.75198918 0.55566688]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами

# Создаем одномерный массив чисел от 0 до 9
array = np.arange(9)

# Преобразуем одномерный массив в двумерную матрицу размером 3x3
matrix_3x3 = array.reshape(3, 3)

# Выводим полученную матрицу
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Создаем матрицу размера 4x4 с единицами на диагонали, смещенной на один наверх
matrix = np.eye(4, k=1)

# Выводим полученную матрицу
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Создаем матрицу 4x4, заполненную семерками
matrix = np.full((4, 4), 7)

# Заполняем главную диагональ числами от 1 до 4
np.fill_diagonal(matrix, np.arange(1, 5))

# Выводим полученную матрицу
print(matrix)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Создаем матрицу размером 5x5, заполненную числами от 0 до 4 в каждой строке
matrix = np.tile(np.arange(5), (5, 1))

# Выводим полученную матрицу
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Шаг 1: Создаем матрицу случайных чисел размера 10x10
matrix = np.random.rand(10, 10)

# Выводим исходную матрицу
print("Исходная матрица:\n", matrix)

# Шаг 2: Вычисляем среднее значение по каждой строке
row_means = matrix.mean(axis=1, keepdims=True)

# Выводим средние значения для каждой строки
print("Средние значения по строкам:\n", row_means)

# Шаг 3: Отнимаем среднее значение каждой строки из элементов этой строки
matrix_centered = matrix - row_means

# Выводим полученную матрицу
print("Матрица после вычитания среднего по строкам:\n", matrix_centered)

Исходная матрица:
 [[0.46010777 0.65802341 0.4375145  0.45070311 0.82163036 0.40317705
  0.18332696 0.2333965  0.51901391 0.89668024]
 [0.35441512 0.52511564 0.35093614 0.83464472 0.95954018 0.61379388
  0.97290487 0.47685565 0.02522653 0.82469798]
 [0.84023895 0.73447547 0.59406583 0.05400815 0.90893256 0.76582536
  0.7228356  0.10788739 0.51412957 0.58690704]
 [0.12481574 0.54263388 0.59925791 0.50907071 0.88230678 0.20262507
  0.91846556 0.31774815 0.19026829 0.94916361]
 [0.0521893  0.56846396 0.74946512 0.73082212 0.19805514 0.53975743
  0.12994219 0.73798028 0.11535423 0.78180719]
 [0.79848044 0.25972842 0.94655218 0.01459723 0.61137008 0.65572808
  0.84406495 0.29508577 0.3659187  0.51831443]
 [0.47448106 0.9524907  0.85116137 0.59386731 0.01573451 0.00934303
  0.00172732 0.28451118 0.61886487 0.99351741]
 [0.63537927 0.35248496 0.80980047 0.51562468 0.87810705 0.63295383
  0.48724325 0.28394825 0.48644449 0.30613563]
 [0.7875644  0.76577218 0.89945095 0.11785252 0.0895115  0.79

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Шаг 1: Создаем матрицу случайных чисел размера 10x10
matrix = np.random.rand(10, 10)

# Выводим исходную матрицу
print("Исходная матрица:\n", matrix)

# Шаг 2: Вычисляем медиану по каждому столбцу
column_medians = np.median(matrix, axis=0, keepdims=True)

# Выводим медианы по столбцам
print("Медианы по столбцам:\n", column_medians)

# Шаг 3: Отнимаем медиану каждого столбца из элементов этого столбца
matrix_centered = matrix - column_medians

# Выводим матрицу после вычитания медиан по столбцам
print("Матрица после вычитания медиан по столбцам:\n", matrix_centered)

Исходная матрица:
 [[0.78609987 0.04978077 0.18951199 0.49278208 0.44465087 0.20401242
  0.98618101 0.46425568 0.14537567 0.72668712]
 [0.57262413 0.22942334 0.37514264 0.93094643 0.48009448 0.5015818
  0.24701814 0.22516253 0.62810296 0.48694883]
 [0.90569003 0.13549855 0.18953765 0.79964046 0.68669216 0.21917113
  0.57751072 0.35575019 0.99121625 0.15366037]
 [0.36096412 0.17212908 0.40945726 0.70702571 0.30187409 0.34918591
  0.128561   0.76990892 0.84596129 0.16464578]
 [0.85193102 0.49995009 0.43496413 0.72888851 0.22064753 0.40677416
  0.92558542 0.5937302  0.3361199  0.0153077 ]
 [0.33237101 0.13615007 0.48707594 0.06391043 0.42546923 0.69507775
  0.15867018 0.67614778 0.56918196 0.40860361]
 [0.61396269 0.39334968 0.72856354 0.87289727 0.40682727 0.35688425
  0.03034968 0.30071531 0.23357554 0.65590385]
 [0.46235926 0.42219072 0.32503229 0.89138848 0.44604921 0.14308253
  0.76408804 0.50580353 0.93692827 0.62151302]
 [0.14381817 0.36874542 0.79464032 0.76764077 0.74472868 0.311

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Шаг 1: Создаем матрицу случайных чисел размером 5x5
matrix = np.random.rand(5, 5)

# Выводим исходную матрицу
print("Исходная матрица 5x5:\n", matrix)

# Шаг 2: Вычисляем максимальные значения по каждой строке
max_in_rows = np.max(matrix, axis=1, keepdims=True)

# Выводим максимальные значения по строкам
print("Максимумы по строкам:\n", max_in_rows)

# Шаг 3: Вычисляем минимальные значения по каждой строке
min_in_rows = np.min(matrix, axis=1, keepdims=True)

# Выводим минимальные значения по строкам
print("Минимумы по строкам:\n", min_in_rows)

# Шаг 4: Добавляем столбцы максимумов и минимумов к исходной матрице
matrix_with_max_min = np.hstack((matrix, max_in_rows, min_in_rows))

# Выводим итоговую матрицу 5x7
print("Матрица 5x7 (с максимумами и минимумами):\n", matrix_with_max_min)


Исходная матрица 5x5:
 [[0.37507614 0.55966975 0.6301328  0.48666402 0.97161716]
 [0.04858107 0.79191879 0.98327482 0.77690823 0.28235671]
 [0.59242748 0.0729777  0.34499433 0.81091496 0.44567824]
 [0.95852526 0.88129227 0.13660347 0.42318206 0.95271848]
 [0.30998481 0.67258701 0.96390466 0.53019432 0.90065366]]
Максимумы по строкам:
 [[0.97161716]
 [0.98327482]
 [0.81091496]
 [0.95852526]
 [0.96390466]]
Минимумы по строкам:
 [[0.37507614]
 [0.04858107]
 [0.0729777 ]
 [0.13660347]
 [0.30998481]]
Матрица 5x7 (с максимумами и минимумами):
 [[0.37507614 0.55966975 0.6301328  0.48666402 0.97161716 0.97161716
  0.37507614]
 [0.04858107 0.79191879 0.98327482 0.77690823 0.28235671 0.98327482
  0.04858107]
 [0.59242748 0.0729777  0.34499433 0.81091496 0.44567824 0.81091496
  0.0729777 ]
 [0.95852526 0.88129227 0.13660347 0.42318206 0.95271848 0.95852526
  0.13660347]
 [0.30998481 0.67258701 0.96390466 0.53019432 0.90065366 0.96390466
  0.30998481]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Шаг 1: Создаем вектор чисел от 1 до 51
vector = np.arange(1, 52)

# Шаг 2: Преобразуем вектор в вектор нечетных чисел и вектор четных чисел
odd_numbers = vector[vector % 2 != 0]  # Нечетные числа
even_numbers = vector[vector % 2 == 0]  # Четные числа

# Выводим векторы нечетных и четных чисел
print("Вектор нечетных чисел:\n", odd_numbers)
print("Вектор четных чисел:\n", even_numbers)

# Шаг 3: Меняем размерности векторов, чтобы получились матрицы
odd_matrix = odd_numbers.reshape(-1, 1)  # Преобразуем в матрицу с одной колонкой
even_matrix = even_numbers.reshape(1, -1)  # Преобразуем в матрицу с одной строкой

# Выводим полученные матрицы
print("Матрица из нечетных чисел:\n", odd_matrix)
print("Матрица из четных чисел:\n", even_matrix)

# Шаг 4: Находим произведение матриц
product_matrix = np.dot(odd_matrix, even_matrix)

# Выводим произведение матриц
print("Произведение матриц:\n", product_matrix)

# Шаг 5: Проверяем, является ли произведение квадратной матрицей и обратимо ли оно
if product_matrix.shape[0] == product_matrix.shape[1]:
    # Шаг 6: Находим обратную матрицу
    inverse_matrix = np.linalg.inv(product_matrix)
    # Выводим обратную матрицу
    print("Обратная матрица:\n", inverse_matrix)
else:
    print("Произведение не является квадратной матрицей, обратная матрица не может быть вычислена.")


Вектор нечетных чисел:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51]
Вектор четных чисел:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Матрица из нечетных чисел:
 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]
 [25]
 [27]
 [29]
 [31]
 [33]
 [35]
 [37]
 [39]
 [41]
 [43]
 [45]
 [47]
 [49]
 [51]]
Матрица из четных чисел:
 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]
Произведение матриц:
 [[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  2

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами и матрицами

# Шаг 1: Создаем пустую матрицу размером 8x8
chessboard = np.zeros((8, 8), dtype=int)

# Шаг 2: Заполняем матрицу в шахматном порядке единицами
chessboard[1::2, ::2] = 1  # Заполняем нечетные строки (1, 3, 5, 7) на четных позициях (0, 2, 4, 6)
chessboard[::2, 1::2] = 1  # Заполняем четные строки (0, 2, 4, 6) на нечетных позициях (1, 3, 5, 7)

# Выводим полученную матрицу
print("Матрица 8x8, заполненная в шахматном порядке нулями и единицами:\n", chessboard)


Матрица 8x8, заполненная в шахматном порядке нулями и единицами:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
